//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace WinLibrary.Entity
{
    using System;

    public partial class Book : INotifyPropertyChanged
    {
        private string _title;
        public long Id { get; set; }

        public string Title
        {
            get { return _title; }
            set
            {
                if (this._title != value)
                {
                    this._title = value;
                    this.NotifyPropertyChanged("Name");
                }
            }
        }

        public string Author { get; set; }
        public string Editor { get; set; }
        public string PublishedYear { get; set; }
        public Nullable<long> PagesNumber { get; set; }


        public event PropertyChangedEventHandler PropertyChanged;

        public void NotifyPropertyChanged(string propName)
        {
            if (this.PropertyChanged != null)
                this.PropertyChanged(this, new PropertyChangedEventArgs(propName));
        }
    }
}
